title: "Shuangshuang Zhao"
description: "PhD student at KAIST, Computer Science & Engineering"
logo: "/assets/images/shuangshuang.zhao.jpg"
locale: "en"
url: "https://poppindouble.github.io"
repository: "poppindouble/poppindouble.github.io"
author:
  name: "Shuangshuang Zhao"
  avatar: "/assets/images/shuangshuang.zhao.jpg"
  bio: "2nd-year PhD student, Computer Science, KAIST"
  location: "KAIST, Daejeon, Korea"
  email: "shuangshuang.zhao@kaist.ac.kr"
  github: "poppindouble"
  # Add other social if needed: scholar, linkedin, etc.

# Minimal Mistakes settings
minimal_mistakes_skin: "default"
search: true
paginate: 5
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
include:
  - _pages

